# Generated by Django 5.2.17 on 2026-09-02 08:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_add_service_category_and_service_product'),
        ('finance', '0001_initial'),
        ('inventory', '0003_product_cost_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='serviceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='service_product_quantity_positive'),
        ),
    ]
