# Generated by Django 5.2.17 on 2026-09-16 12:54

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_service_compensation_role'),
        ('finance', '0002_update_service_item_constraints'),
        ('inventory', '0003_product_cost_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor (Injections)'), ('facial', 'Facial Worker'), ('laser', 'Laser Tech')], max_length=20, unique=True)),
                ('payout_type', models.CharField(choices=[('cash', 'Cash Only'), ('product', 'Product Only'), ('hybrid', 'Cash + Product')], default='cash', max_length=20)),
                ('calculation_type', models.CharField(choices=[('percent_profit', '% of Profit'), ('fixed_per_session', 'Fixed per Session'), ('monthly_salary', 'Monthly Salary')], default='percent_profit', max_length=20)),
                ('percent_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of profit (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('fixed_amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed USD amount per session', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fixed_amount_toman', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed Toman amount per session (alternative to USD)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transport allowance per session (USD)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transport allowance per session (Toman)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('product_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_rules', to='inventory.product')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor (Injections)'), ('facial', 'Facial Worker'), ('laser', 'Laser Tech')], max_length=20)),
                ('revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('revenue_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('product_cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('product_cost_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payout_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payout_cash_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payout_product_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('payout_product_value_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payout_product_value_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payout_mode', models.CharField(choices=[('cash', 'Cash'), ('product', 'Product')], default='cash', max_length=10)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('payout_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payouts', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payouts', to='customers.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payouts', to='customers.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff', '-created_at'], name='finance_sta_staff_i_541cdd_idx'), models.Index(fields=['visit', 'staff'], name='finance_sta_visit_i_6f7c9c_idx'), models.Index(fields=['status', '-created_at'], name='finance_sta_status_58dbf0_idx'), models.Index(fields=['role', '-created_at'], name='finance_sta_role_3b8cde_idx')],
                'constraints': [models.UniqueConstraint(fields=('visit', 'staff', 'service'), name='uniq_payout_per_visit_staff_service')],
            },
        ),
    ]
