# Generated by Django 5.2.17 on 2026-09-21 09:08

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_staffcompensationrule_staffpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'operating expense categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order', 'name'], name='opex_cat_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Toman-per-USD snapshot captured at creation; never recalculated.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Toman snapshot derived from amount_usd and the creation-time rate.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expense_date', models.DateField(help_text='Business date of the expenditure (Gregorian, finance convention).')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('receipt', models.FileField(blank=True, null=True, upload_to='operating_expenses/%Y/%m/')),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('idempotency_key', models.CharField(blank=True, help_text='Client-supplied key; repeat submissions return the original record.', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses', to='finance.operatingexpensecategory')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='opex_date_idx'), models.Index(fields=['category', 'expense_date'], name='opex_cat_date_idx'), models.Index(fields=['payment_method', 'expense_date'], name='opex_method_date_idx'), models.Index(fields=['created_by', 'expense_date'], name='opex_creator_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_usd__gte', Decimal('0'))), name='opex_amount_non_negative')],
            },
        ),
    ]
