# Generated by Django 5.2.17 on 2026-09-21 09:08

from django.db import migrations

SEED_CATEGORIES = [
    ('Office Supplies', 'office-supplies', 10),
    ('Cleaning & Hygiene', 'cleaning-hygiene', 20),
    ('Customer Refreshments', 'customer-refreshments', 30),
    ('Utilities', 'utilities', 40),
    ('Rent', 'rent', 50),
    ('Maintenance & Repairs', 'maintenance-repairs', 60),
    ('Marketing', 'marketing', 70),
    ('Equipment', 'equipment', 80),
    ('Internet & Telephone', 'internet-telephone', 90),
    ('Other', 'other', 100),
]


def seed_categories(apps, schema_editor):
    OperatingExpenseCategory = apps.get_model('finance', 'OperatingExpenseCategory')
    for name, slug, sort_order in SEED_CATEGORIES:
        OperatingExpenseCategory.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


def unseed_categories(apps, schema_editor):
    """No-op on reverse: seeded rows may already be referenced by real
    operating expenses, and deleting financial reference data on a down
    migration would be unsafe. Deactivate manually instead."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_operatingexpensecategory_operatingexpense'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
