# Generated by Django 5.2.17 on 2026-09-22 12:33

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_service_compensation_role'),
        ('finance', '0005_seed_operating_expense_categories'),
        ('inventory', '0003_product_cost_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_packs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WelcomePackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_pack_usages', to='inventory.product')),
                ('welcome_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.welcomepack')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomePackUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_cost_usd_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost_toman_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welcome_pack_usages', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_pack_usages_issued', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_pack_usages', to='customers.visit')),
                ('welcome_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='finance.welcomepack')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='welcomepack',
            index=models.Index(fields=['is_active', 'name'], name='welcomepack_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='welcomepackitem',
            index=models.Index(fields=['welcome_pack', 'product'], name='welcomepack_item_pack_prod_idx'),
        ),
        migrations.AddConstraint(
            model_name='welcomepackitem',
            constraint=models.UniqueConstraint(fields=('welcome_pack', 'product'), name='uniq_welcomepack_item'),
        ),
        migrations.AddConstraint(
            model_name='welcomepackitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='welcomepack_item_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='welcomepackusage',
            index=models.Index(fields=['issued_at'], name='wp_usage_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='welcomepackusage',
            index=models.Index(fields=['customer', 'issued_at'], name='wp_usage_cust_date_idx'),
        ),
        migrations.AddIndex(
            model_name='welcomepackusage',
            index=models.Index(fields=['welcome_pack', 'issued_at'], name='wp_usage_pack_date_idx'),
        ),
    ]
