# Generated by Django 5.2.17 on 2026-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_service_compensation_role'),
        ('finance', '0006_welcomepack_welcomepackitem_welcomepackusage_and_more'),
        ('inventory', '0004_product_brand_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='is_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='selection_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['service', 'selection_group'], name='finance_ser_service_94d791_idx'),
        ),
    ]
