# Generated by Django 5.2.17 on 2026-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_productusage_is_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcomponent',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash (USD)'), ('cash_toman', 'Cash (Toman)'), ('cash_usd', 'Cash (USD)'), ('card', 'Card'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
