# Generated by Django 5.2.17 on 2026-09-29 10:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_service_compensation_role'),
        ('finance', '0009_purchaseorder_purchaseorderitem_and_more'),
        ('inventory', '0005_alter_product_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCompensationRuleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayoutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('value_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('value_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='staffpayout',
            name='payout_kind',
            field=models.CharField(choices=[('session', 'Per Visit'), ('monthly_salary', 'Monthly Salary')], default='session', help_text='SESSION pays per visit; MONTHLY_SALARY pays once per salary_period.', max_length=20),
        ),
        migrations.AddField(
            model_name='staffpayout',
            name='salary_period',
            field=models.DateField(blank=True, help_text='First day of the salary month. Set only for MONTHLY_SALARY payouts.', null=True),
        ),
        migrations.AlterField(
            model_name='staffcompensationrule',
            name='fixed_amount_toman',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed Toman amount per session, or the monthly salary when calculation_type is monthly_salary (alternative to USD)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='staffcompensationrule',
            name='fixed_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed USD amount per session, or the monthly salary when calculation_type is monthly_salary', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='staffpayout',
            name='payout_product_value_toman',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total Toman value of all payout product lines', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='staffpayout',
            name='payout_product_value_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total value of all payout product lines', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='staffpayout',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_kind', 'monthly_salary')), fields=('staff', 'role', 'salary_period'), name='uniq_monthly_salary_payout_per_period'),
        ),
        migrations.AddField(
            model_name='staffcompensationruleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_rule_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='staffcompensationruleproduct',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='finance.staffcompensationrule'),
        ),
        migrations.AddField(
            model_name='staffpayoutproduct',
            name='payout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='finance.staffpayout'),
        ),
        migrations.AddField(
            model_name='staffpayoutproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payout_lines', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='staffcompensationruleproduct',
            constraint=models.UniqueConstraint(fields=('rule', 'product'), name='uniq_compensation_rule_product'),
        ),
        migrations.AddConstraint(
            model_name='staffcompensationruleproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='compensation_rule_product_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffpayoutproduct',
            constraint=models.UniqueConstraint(fields=('payout', 'product'), name='uniq_payout_product'),
        ),
        migrations.AddConstraint(
            model_name='staffpayoutproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='payout_product_qty_positive'),
        ),
    ]
