# Generated by Django 5.2.17 on 2026-09-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_backfill_staff_rule_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='welcome_pack_usage',
            field=models.ForeignKey(blank=True, help_text='Set when the consumption was caused by issuing a free welcome pack.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='finance.welcomepackusage'),
        ),
    ]
