# Generated by Django 5.2.17 on 2026-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepackusage',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-supplied key; a repeated issuance returns the original record instead of deducting stock again.', max_length=64, null=True, unique=True),
        ),
    ]
