"""Seed the clinic's staff compensation rules.

The rules are the clinic's stated terms and the existing
``StaffCompensationRule`` model already represents all three, so this is a data
migration rather than a schema change:

    doctor  -> 50% of the profit generated by the doctor's own services
    facial  -> 30% of the profit generated by the facial operator's own services
    laser   -> 18,000,000 Toman/month base + 8,000,000 Toman/month transport

Idempotent: a missing row is created, and a rule that already carries a
configured percentage is never overwritten with a different one. ``role`` is
unique, so re-running is safe. No-op on reverse: removing these rules would
silently stop staff compensation.
"""
from decimal import Decimal

from django.db import migrations

# Literal choice values: a historical model in a data migration does not expose
# the nested TextChoices classes.
PERCENT_PROFIT = 'percent_profit'
MONTHLY_SALARY = 'monthly_salary'
CASH = 'cash'
DOCTOR = 'doctor'
FACIAL = 'facial'
LASER = 'laser'

LASER_BASE_TOMAN = Decimal('18000000')
LASER_TRANSPORT_TOMAN = Decimal('8000000')


def seed_rules(apps, schema_editor):
    Rule = apps.get_model('finance', 'StaffCompensationRule')

    for role, percent in ((DOCTOR, Decimal('50.00')), (FACIAL, Decimal('30.00'))):
        rule, created = Rule.objects.get_or_create(role=role)
        changed = False
        if created or rule.calculation_type != PERCENT_PROFIT:
            rule.calculation_type = PERCENT_PROFIT
            changed = True
        # Only fill a missing percentage; an operator's tuned value is kept.
        if rule.percent_profit is None:
            rule.percent_profit = percent
            changed = True
        if created:
            rule.payout_type = CASH
            rule.is_active = True
            changed = True
        if changed:
            rule.save()

    rule, created = Rule.objects.get_or_create(role=LASER)
    changed = False
    if created:
        rule.calculation_type = MONTHLY_SALARY
        rule.fixed_amount_toman = LASER_BASE_TOMAN
        rule.transport_toman = LASER_TRANSPORT_TOMAN
        rule.payout_type = CASH
        rule.is_active = True
        changed = True
    elif rule.calculation_type != MONTHLY_SALARY:
        # A laser operator is a fixed monthly cost, never a percentage of a
        # visit. Only convert when no monthly salary was configured yet.
        if rule.fixed_amount_toman is None and rule.fixed_amount_usd is None:
            rule.calculation_type = MONTHLY_SALARY
            rule.fixed_amount_toman = LASER_BASE_TOMAN
            rule.transport_toman = LASER_TRANSPORT_TOMAN
            changed = True
    if changed:
        rule.save()


def unseed_rules(apps, schema_editor):
    """Intentionally empty: these rules drive real payouts."""


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_welcomepackusage_idempotency_key'),
    ]

    operations = [
        migrations.RunPython(seed_rules, unseed_rules),
    ]