# Generated by Django 5.2.17 on 2026-09-24 11:38

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_analyses/%Y/%m/')),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('symmetry_score', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('skin_clarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('youthfulness_score', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('harmony_score', models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('detected_attributes', models.JSONField(default=dict, help_text='Face shape, skin tone, undertone, eye shape, lip fullness, etc.')),
                ('suggestions', models.JSONField(default=list, help_text='List of {category, title, detail} objects.')),
                ('raw_model_output', models.JSONField(default=dict, help_text='Full provider payload for debugging.')),
                ('provider', models.CharField(choices=[('local', 'Local (MediaPipe)'), ('external', 'External API')], max_length=32)),
                ('model_version', models.CharField(blank=True, max_length=64, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='face_analyz_user_id_dd8cd0_idx'), models.Index(fields=['created_at'], name='face_analyz_created_18b37f_idx')],
            },
        ),
    ]
