# Generated by Django 5.2.17 on 2026-09-24 13:26

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_service_compensation_role'),
        ('face_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal')], max_length=20)),
                ('primary_concerns', models.JSONField(default=list, help_text='Top concerns in priority order, e.g. ["acne", "dullness"].')),
                ('recommended_frequency', models.CharField(max_length=120, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('provider', models.CharField(choices=[('rule_based', 'Rule based'), ('llm', 'LLM')], max_length=20)),
                ('model_used', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_plan', to='face_analyzer.faceanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinCareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('weekly', 'Weekly'), ('lifestyle', 'Lifestyle'), ('professional', 'Professional')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('description', models.TextField(validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('exfoliant', 'Exfoliant'), ('mask', 'Mask'), ('eye_care', 'Eye care'), ('treatment', 'Treatment'), ('lifestyle', 'Lifestyle'), ('diet', 'Diet'), ('in_clinic', 'In-clinic')], max_length=20)),
                ('key_ingredients', models.JSONField(default=list)),
                ('avoid_ingredients', models.JSONField(default=list)),
                ('related_service_slug', models.CharField(blank=True, default='', max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_tips', to='face_analyzer.faceanalysis')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='face_analyzer.skincareplan')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_tips', to='customers.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
