# Generated by Django 5.0.14 on 2026-06-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicuser',
            options={'ordering': ['username']},
        ),
    ]
