# Generated by Django 5.2.17 on 2026-08-25 13:48

import Sefro_Clinic.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clinicuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='clinicuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='clinicuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MaxLengthValidator(150), django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
    ]
