# Generated by Django 5.2.17 on 2026-08-29 07:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockmovement_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current clinic acquisition cost in USD. Historical costs are tracked via ProductCostHistory.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
