# Generated by Django 5.2.17 on 2026-09-22 15:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('treatment', 'Treatment'), ('consumable', 'Consumable'), ('other', 'Other')], db_index=True, default='treatment', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
