# Generated by Django 5.0.14 on 2026-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='end_at_shamsi',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_at_shamsi',
        ),
    ]
