# Generated by Django 5.0.14 on 2026-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_visit_end_at_shamsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bitmoji_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
