# Generated by Django 5.0.14 on 2026-06-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_service_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer satisfaction rating 1-5', null=True),
        ),
    ]
