# Generated by Django 5.2.7 on 2026-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_satisfaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
            ],
            options={
                "verbose_name": "زمان کاری",
                "verbose_name_plural": "ساعات کاری",
            },
        ),
    ]
