# Generated by Django 5.0.14 on 2026-08-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_worktime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkTime',
        ),
    ]
