# Generated by Django 5.2.17 on 2026-08-25 13:48

import Sefro_Clinic.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_delete_worktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bitmoji_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
    ]
