# Generated by Django 5.2.17 on 2026-08-27 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_bitmoji_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payments_paid_at_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['start_at'], name='visits_start_at_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['customer', 'start_at', 'end_at'], name='visit_overlap_idx'),
        ),
    ]
