# Generated by Django 5.2.17 on 2026-08-29 07:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_perf_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD snapshot of the paid amount, when recorded through the financial system.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Toman-per-USD exchange rate snapshot at payment time.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='USD base price. Authoritative for the financial system; "price" is the legacy display value.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
