# Generated by Django 5.2.17 on 2026-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_payment_amount_usd_payment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('wallet', 'Wallet'), ('mixed', 'Mixed')], default='card', max_length=20),
        ),
    ]
