# Generated by Django 5.2.17 on 2026-09-02 08:57

import Sefro_Clinic.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='customers.servicecategory'),
        ),
    ]
