# Generated by Django 5.2.17 on 2026-09-16 11:35

import Sefro_Clinic.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_add_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file_sys_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), Sefro_Clinic.validators._reject_surrogates]),
        ),
    ]
