# Generated by Django 5.2.17 on 2026-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customer_file_sys_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='compensation_role',
            field=models.CharField(choices=[('none', 'No Commission'), ('doctor', 'Doctor (Injections)'), ('facial', 'Facial Worker'), ('laser', 'Laser Tech')], default='none', help_text='Determines which staff role receives commission for this service', max_length=20),
        ),
    ]
